[tool.micropython-stubber]
mpy-stubs-repo-path = "."
stub-path = "./stubs"
publish-path = "./publish"
template-path = "./publish/template"

[tool.black]
# use same config as -stubber
line-length = 140
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
    /(
        | tests
    )/
)
'''
