name: "stub-diff"
description: "determine if there are changes to the stubs"
inputs:
  path:
    description: the path in the repo to check for changes
    required: false
    default: "./stubs"
  pattern:
    description: "the pattern to match"
    required: false
    default: ".py"

  # summary:
  #   description: generate a summary of the changes
  #   required: false
  #   default: 'true'

outputs:
  changed:
    description: "true if changes have been detected, false otherwise"
    value: ${{ steps.diff.outputs.changed }}
  count:
    description: "the number of detected changes"
    value: ${{ steps.diff.outputs.count }}

runs:
  using: composite
  steps:
    - name: check for changes using git diff
      shell: pwsh
      id: diff
      run: |
        .github/actions/stub-diff/git-diff.ps1 -path ${{inputs.path}} -pattern ${{inputs.pattern}}

    # - name: Commit the changes
    #   uses: EndBug/add-and-commit@v8
    #   with:
    #     message: ${{ inputs.message }}
