name: "stub-diff"
description: "determine if there are changes to the stubs"

outputs:
  changed:
    description: "true if changes have been detected, false otherwise"
    value: ${{ steps.diff.outputs.changed }}
  count:
    description: "the number of detected changes"
    value: ${{ steps.diff.outputs.count }}

runs:
  using: composite
  steps:
    - name: check for changes using git diff
      shell: pwsh
      working-directory: ${{ github.workspace }}
      id: diff
      run: |
        .github/actions/stub-diff/git-diff.ps1

