name: Createstubs

on: [push, workflow_dispatch]

jobs:
  createstubs:
    runs-on: self-hosted
    steps:
    - name: Checkout stubs repo
      uses: actions/checkout@v4
    - name: Checkout stubber repo (scripts)
      uses: actions/checkout@v4
      with:
        repository: josverl/micropython-stubber
        path: repos/micropython-stubber
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: 3.11
          cache: pip
    - name: Install dependencies
      run: |
        pip install -U mpremote micropython-stubber
        pipx install poetry

    - name: clone Repos
      run: |
        stubber clone

    - name: run board stubber 
      run: |
        stubber get-mcu-stubs

    - name: check in changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "create boardstubs"
        git push    
