name: Createstubs

on: [push, workflow_dispatch]

jobs:
  createstubs:
    runs-on: self-hosted
    strategy:
      matrix:
        version: [preview, v1.22.2]
    steps:
      - name: Checkout stubs repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
          
      - name: Install dependencies
        run: |
          pipx install poetry
          pip install -U mpremote micropython-stubber

      - name: Install mp_downloader
        run: |
          # dev versie 
          pip install -I git+https://github.com/josverl/micropython-stubber.git@action_board_stubber#subdirectory=src/mptool

      - uses: actions/cache@v4
        with:
          path: firmware
          key: firmware

      - name: Get Preview firmwares for flashing
        run: |
          mptool download --version ${{ matrix.version }} --preview

      # - uses: actions/cache/save@v4
      #   with:
      #       path: firmware
      #       key: firmware

      - name: Update firmware to the most recent preview-build on all connected boards
        # cant update stm32 as that requires sudo :-( 
        run: |
          mptool flash --version ${{ matrix.version }}

      - name: clone Repos
        run: |
          stubber clone

      - name: run board stubber
        run: |
          stubber get-mcu-stubs

      - name: check in changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "create boardstubs"
          git push
