name: Createstubs

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Checkout stubber  repo
      uses: actions/checkout@v4
      with:
        repository: josverl/micropython-stubber
        path: repos/micropython-stubber
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: 3.11
          cache: pip
    - name: Install dependencies
      run: |
        pip install -U mpremote micropython-stubber
        pipx install poetry
    - name: clone Repos
      run: |
        stubber clone

    - name: run board stubber 
      # working-directory: repos/micropython-stubber
      run: |
        python3 repos/micropython-stubber/scripts/board_stubber.py
