name: Createstubs

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install -U mpremote micropython-stubber
      
    - name: list connected devices
      run: |
        mpremote devs
