########################################################################################################################################
# This will attempt to retrieve and generate stubs from MicroPython documentation
########################################################################################################################################
# Check out repos in this structure 
# micropython-stubs
#     + - stubs 
#   +-- micropython-stubber
#       +-- micropython
#        -- micropython-lib
# repro structure needed to allow automatic PR creation to work
########################################################################################################################################
name: get-doc-stubs

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 1 * * 5"   # Run every Friday at 01:00

jobs:
  ########################################################################################################################################
  get-micropython-doc-stubs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        version: ['v1.17','v1.18','v1.19','v2.0','Latest']
        # version: ['v1.15','v1.16','v1.17','Latest','fix_lib_documentation']

    # Most scripts will be run from the stubber, set that as default
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/micropython-stubber
  
    steps:

      - name: Checkout stubs repo
        uses: actions/checkout@v2

      - name: Checkout Stubber
        uses: actions/checkout@v2
        with:
          repository: josverl/micropython-stubber
          path: micropython-stubber

      - name: Checkout stubber submodules
        working-directory: ${{github.workspace}}/micropython-stubber
        run: git submodule update --init 

      - name: sync with micropython upstream 
        working-directory: ${{github.workspace}}/micropython-stubber/micropython
        run: |
          git remote add --tags micropython https://github.com/micropython/micropython.git
          git fetch --all --tags

      # micropython as a sub-module of micropython-stubber 
      - name: 'checkout micropython  ${{ matrix.version }}'
        if: matrix.version!='Latest'
        working-directory: ${{github.workspace}}/micropython-stubber/micropython
        run: |
          git checkout ${{ matrix.version }}

      - name: Latest checkout micropython/master
        if: matrix.version=='Latest'
        working-directory: ${{github.workspace}}/micropython-stubber/micropython
        run: |
          git checkout micropython/master

      - name: get commit info
        id: mpycommit
        working-directory: ${{github.workspace}}/micropython-stubber/micropython
        run: |
          echo "::set-output name=info::'$(git log --oneline -1)'"

     
      # make Python work
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      #----------------------------------------------
      # poetry is not in the default image
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      # install dependencies 
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      #----------------------------------------------
      # install root project Pymakr
      #----------------------------------------------
      - name: Install library stubber
        run: poetry install --no-interaction

      ######################################
      # This is where the actual work starts
      ######################################

      - name: Generate document stubs for ${{ matrix.version }}
        working-directory: ${{github.workspace}}/micropython-stubber
        run: |
          get_docstubs --stub-folder ${{github.workspace}}/stubs 

      - name: Create Pull Request
        # id: cpr-doc
        uses: peter-evans/create-pull-request@v3
        # ref: https://github.com/peter-evans/create-pull-request
        with:
          token: ${{ secrets.CREATE_PR_ACTION_TOKEN }} 
          title: "Add/update MicroPython ${{ matrix.version }} doc-stubs"
          commit-message: add/update doc-stubs
          body : |
            update MicroPython ${{ matrix.version }} doc-stubs
            based on micropython commit ${{ steps.mpycommit.outputs.info }}


          branch: "micropython-${{ matrix.version }}-doc-stubs"
          reviewers: josverl
          labels: |
            automated pr
            Doc stubs 
            MicroPython
            ${{ matrix.version }}
          # delete-branch: true
