########################################################################################################################################
# This will attempt to retrieve and generate stubs from MicroPython documentation
########################################################################################################################################
# Check out repos in this structure 
# micropython-stubs
# +-- stubs 
# +-- repos 
#     +-- micropython
#      -- micropython-lib
# repro structure needed to allow automatic PR creation to work
########################################################################################################################################
name: get-doc-stubs

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 1 * * 5"   # Run every Friday at 01:00

jobs:
  ########################################################################################################################################
  get-micropython-doc-stubs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        version: ['v1.17','v1.18','v1.19','v2.0','Latest']
        # version: ['v1.15','v1.16','v1.17','Latest','fix_lib_documentation']

    # Most scripts will be run from the stubber, set that as default
    defaults:
      run:
        shell: bash
  
    steps:

      - name: Checkout stubs repo
        uses: actions/checkout@v2

      # make Python work
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Python dependencies (stubber)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # micropython as a sub-module 
      - name: 'clone and checkout micropython ${{ matrix.version }}'
        run: |
          stubber clone
          stubber switch --tag ${{ matrix.version }}

      ######################################
      # This is where the actual work starts
      ######################################

      - name: Generate document stubs for ${{ matrix.version }}
        run: |
          stubber get-docstubs


      - name: check for changes other than modules.py
        shell: pwsh
        id: changed
        run: |
          $changed = @(git whatchanged -1 --format=oneline  | ?{ $_.Contains(".py") })
          write-host "Changed stub files:"
          write-host $changed
          write-host "::set-output name=count::$($changed.count)"

      - name: Create Pull Request ( if relevant changes) 
        if: ${{ steps.changed.outputs.count }} >= 1
        id: cpr-doc
        uses: peter-evans/create-pull-request@v3
        # ref: https://github.com/peter-evans/create-pull-request
        with:
          token: ${{ secrets.CREATE_PR_ACTION_TOKEN }} 
          title: "Add/update MicroPython ${{ matrix.version }} doc-stubs"
          commit-message: add/update doc-stubs
          body : |
            update MicroPython ${{ matrix.version }} doc-stubs
            based on micropython commit ${{ steps.mpycommit.outputs.info }}

          branch: "micropython-${{ matrix.version }}-doc-stubs"
          labels: |
            automated pr
            Doc stubs 
            MicroPython
            ${{ matrix.version }}
          delete-branch: true

      - name: done
        if: always()
        run: |
          echo "Done..."
