########################################################################################################################################
# This will attempt to retrieve and generate stubs from all known versions of MicroPython
########################################################################################################################################
# Check out repos in this structure
# micropython-stubs
#   + - stubs
########################################################################################################################################
name: get-loboris-frozen

on:
  workflow_dispatch:
  # not maintained- no need to try to update all the time
  # schedule:
  #   - cron: "0 1 * * *"   # Run everyday at 01:00
env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  ########################################################################################################################################
  get-loboris-frozen-stubs:
    runs-on: ubuntu-latest

    # Most scripts will be run from the stubber, set that as default
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout stubs repo
        uses: actions/checkout@v3

      # make Python work
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies (stubber)
        run: |
          pip install --upgrade wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      ######################################
      # This is where the actual work starts
      ######################################

      - name: Get frozen modules for ${{ matrix.version }}
        run: |
          stubber get-lobo --black

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        # ref: https://github.com/peter-evans/create-pull-request
        with:
          token: ${{ secrets.CREATE_PR_ACTION_TOKEN }} # ${{ secrets.PAT }}
          title: "add/update Loboris frozen stubs"
          commit-message: add/update Loboris frozen stubs
          branch: "micropython-lobo-stubs"
          labels: |
            frozen stubs
            Loboris
          delete-branch: true

      - name: done
        if: always()
        run: |
          echo "Done..."

  ########################################################################################################################################
