########################################################################################################################################
# This will attempt to retrieve and generate stubs from all known versions of MicroPython
########################################################################################################################################
# Check out repos in this structure 
# micropython-stubs
#   + - stubs 
#   +-- micropython-stubber
#       +-- micropython
#        -- micropython-lib
# repro structure needed to allow automatic PR creation to work
########################################################################################################################################
name: get-loboris-frozen

on:
  workflow_dispatch:
  # not maintained- no need to try to update all the time 
  # schedule: 
  #   - cron: "0 1 * * *"   # Run everyday at 01:00

jobs:
  ########################################################################################################################################
  get-loboris-frozen-stubs:
    runs-on: ubuntu-latest

    # Most scripts will be run from the stubber, set that as default
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/micropython-stubber
    
    steps:

      - name: Checkout stubs repo
        uses: actions/checkout@v2

      - name: Checkout Stubber
        uses: actions/checkout@v2
        with:
          repository: josverl/micropython-stubber
          path: micropython-stubber

      # make Python work
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: restore Python from cache 
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('micropython-stubber/requirements.txt') }}

      - name: Install Python dependencies (stubber)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      ######################################
      # This is where the actual work starts
      ######################################

      - name: Get frozen modules for ${{ matrix.version }}
        working-directory: ${{github.workspace}}/micropython-stubber
        run: |
          python ./src/get_all_frozen.py --stub-folder ${{github.workspace}}/stubs --lobo

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        # ref: https://github.com/peter-evans/create-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ${{ secrets.PAT }}
          title: "add/update Loboris frozen stubs"
          commit-message: add/update Loboris frozen stubs
          branch: "micropython-lobo-stubs"
          reviewers: josverl
          labels: |
            frozen stubs
            Loboris
          delete-branch: true
  ########################################################################################################################################

