name: matrix
on: push
jobs:
  job10:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT


  job20:
    needs: job10
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job10.outputs.matrix) }}
    steps:
      - run: echo {{ matrix.project}}